os: linux
language: python
sudo: true
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
  matrix:
    - TOX_ENV=py36
    - TOX_ENV=py37
before_install:
  - sudo -u postgres psql -c "CREATE USER gandalf WITH PASSWORD 'gandalf'"
  - sudo -u postgres psql -c "ALTER ROLE gandalf SUPERUSER"
  - sudo -u postgres psql -c "CREATE DATABASE gandalf_test"
install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install codecov
script:
  - tox
after_success:
  - codecov
