os: linux
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,flake8,tests
    - python: 3.7
      env: TOXENV=py37,flake8,tests
install:
  - pip install tox
  - pip install -r requirements-dev.in
  - pip install codecov
script:
  - tox
after_success:
  - codecov
